---

#spring:
#  profiles: inmemory
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  datasource:
#      url: jdbc:h2:mem:testdb
#      username: sa
#      password:
#      driver-class-name: org.h2.Driver
#      initialization-mode: always
#      platform: h2
#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
#        hbm2ddl:
#          import_files: data.sql


---